name: Linting and Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install pnpm packages
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint
